patchworkpp_node:
  ros__parameters:
    # ROS node configuration
    base_frame: "velodyne"
    use_sim_time: true
    
    # Patchwork++ configuration
    sensor_height: 0.3
    num_iter: 3
    num_lpr: 20
    num_min_pts: 10
    th_seeds: 0.3
    th_dist: 0.125
    th_seeds_v: 0.25
    th_dist_v: 0.9
    max_range: 80.0
    min_range: 0.3
    uprightness_thr: 0.101
    verbose: true
    
    # ROI Filtering Parameters (ROI)
    # Filter out points outside this box
    roi_x_min: 0.5    # Forward distance min (m)
    roi_x_max: 20.0   # Forward distance max (m)
    roi_y_min: -3.0   # Left limit (m)
    roi_y_max: 3.0    # Right limit (m)
    roi_z_min: -0.5   # Height min (m) - slightly below ground to catch slopes? 
                      # Wait, if we use this for non-ground, we want objects ON ground.
                      # Ground is removed by Patchwork++. 
                      # Objects usually start from z > ground_z.
                      # Let's set default carefully. 
    roi_z_max: 2.0    # Height max (m)
